version: '3.3'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./.docker/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'd3v3L0pm3nt_S3rv3r!'
    ports:
      - "5432:5432"
    networks:
      - app-network
  server:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./services/backend:/var/www
      - ./.docker/server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
      - "8000:8000"
    networks:
      - app-network
  api:
    build: ./services/backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./services/backend:/var/www
      - ./.docker/api/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - app-network
  site:
    build: ./services/site
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local